### ISSUE TITLE
could you tell me how to run the front-end in '/static'

### ISSUE THREAD

**Issue by MattGong** [honmaple/flask-apscheduler#1]
hi, i'm interested in this project. Could you tell me how to run the front-end in '/static', thanks you.

**Comment by honmaple** [comment]
Thank you for your interest in this project,I used  'vue-cli' to create front-end project,please see [https://github.com/vuejs/vue-cli](https://github.com/vuejs/vue-cli),then remember to install **vue-resource**

but I have not finish this project yet
